# Generated by Django 3.2.15 on 2023-07-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
