# Generated by Django 3.2.15 on 2023-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='refresh',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
    ]
